package com.project926.backend.dto;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;

import java.util.UUID;

/**
 * Mirrors the existing verify route's success response exactly:
 * {@code { success, bookingId, reference, qrCode }}.
 *
 * qrCode is the "data:image/png;base64,..." data URL generated by
 * QrCodeGenerator and persisted via confirm_booking_and_commit_inventory's
 * p_qr_code parameter (Phase E) — exactly matching the existing route's
 * {@code qrDataUrl}. (In Phase D this was always null, since QR generation
 * was explicitly out of scope for that phase; see the Phase D report.)
 */
@JsonNaming(PropertyNamingStrategies.LowerCamelCaseStrategy.class)
public record VerifyPaymentResponse(
    boolean success,
    UUID bookingId,
    String reference,
    String qrCode
) {
}
